Home
TanyaStk/Netflix pull request #6
Opened 2022-05-31 13:41 UTC by TanyaStk

2022-05-31 15:38 UTC, dnv190 approved these changes

2022-06-01 14:31 UTC, TanyaStk commented
![Simulator Screen Shot - iPhone 11 - 2022-06-01 at 17 31 09](https://user-images.githubusercontent.com/64659217/171429332-690a13cb-7484-43d1-9f8a-787a8ceed6e1.png)

2022-06-01 14:57 UTC, dnv190 requested changes
Hey, 
Left some notes - the UI is mostly done right 👍

2022-06-01 14:57 UTC, dnv190 commented on Netflix/Info.plist
> +		<string>Mansalva-Regular.ttf</string>
Wow 👍 
tbh, I was thinking that fonts are optional for the internership ;) 
Nice

2022-06-01 14:57 UTC, dnv190 commented on Netflix/Screens/Dashboard/Home/HomeCollectionViewCell.swift
> +    static let identifier = "HomeTableViewCell"
[Optional]
Alternative - https://github.com/AliSoftware/Reusable

2022-06-01 14:57 UTC, dnv190 commented on Netflix/Screens/Dashboard/Home/HomeCollectionViewCell.swift
> +        addSubview(filmCoverImageView)
You should never ever add something to the UITableViewCell 😨 
There is a contentView, please use it - otherwise, you may really weird behavior

2022-06-01 14:57 UTC, dnv190 commented on Netflix/Screens/Dashboard/Home/HomeViewController.swift
> +    }()
```suggestion
    private let latestFilmImageView  UIImage(named: Asset.Assets.filmCover.name)
```

2022-06-01 14:57 UTC, dnv190 commented on Netflix/Screens/Dashboard/Home/HomeViewController.swift
> +        label.font = UIFont(name: "Mansalva-Regular", size: 48)
You can use SwiftGen for the fonts as well

2022-06-01 14:57 UTC, dnv190 commented on Netflix/Screens/Dashboard/Home/HomeViewController.swift
> +        popularMoviesCollection.dataSource = self
To keep all collectionRelated staff in one place
```suggestion
    private lazy var popularMoviesCollection: UICollectionView = {
        let layout = UICollectionViewFlowLayout()
        layout.scrollDirection = .horizontal
        let collectionView = UICollectionView(frame: .zero, collectionViewLayout: layout)
         popularMoviesCollection.delegate = self
        popularMoviesCollection.dataSource = self
        collectionView.register(HomeCollectionViewCell.self, forCellWithReuseIdentifier: HomeCollectionViewCell.identifier)
        return collectionView
    }()
    
    override func viewDidLoad() {
        super.viewDidLoad()
```

2022-06-01 14:57 UTC, dnv190 commented on Netflix/Screens/Dashboard/Home/HomeViewController.swift
> +    }
🛑 
You haven't invoked `super.viewDidLayoutSubviews`

Also, you are adding NEW gradient every time you view layouts - it's a leak

2022-06-01 14:57 UTC, dnv190 commented on Netflix/Screens/Dashboard/Home/HomeViewController.swift
> +    }
I can suggest to create a gradient view instead 🤔 
Or to layout the existing layer

2022-06-06 06:03 UTC, merged